#!/usr/bin/env python3
"""
postgres-intelligence .env setup wizard.
"""

from __future__ import annotations

import getpass
import sys
from pathlib import Path
from typing import Dict, List, Optional


try:
    import psycopg
except ImportError as exc:  # pragma: no cover - dependency guidance
    raise SystemExit(
        'Missing dependency: install with python3 -m pip install "psycopg[binary]"'
    ) from exc


def get_input(prompt: str, default: Optional[str] = None, secret: bool = False) -> str:
    label = f"{prompt} [{default}]: " if default else f"{prompt}: "
    value = getpass.getpass(label) if secret else input(label)
    return value.strip() or (default or "")


def test_connection(config: Dict[str, str]) -> tuple[bool, str]:
    try:
        with psycopg.connect(
            host=config["host"],
            port=int(config["port"]),
            user=config["user"],
            password=config["password"],
            dbname=config["database"],
            sslmode=config["sslmode"],
            connect_timeout=int(config["connect_timeout"]),
            application_name=config["application_name"],
            autocommit=True,
        ) as conn:
            with conn.cursor() as cursor:
                cursor.execute("SELECT current_database(), current_schema()")
                database_name, schema_name = cursor.fetchone()
        return True, f"Connection successful: {database_name}.{schema_name}"
    except Exception as error:
        return False, str(error)


def setup_database_config(db_num: int) -> Optional[Dict[str, str]]:
    print("\n" + "=" * 60)
    print(f"  DATABASE {db_num} CONFIGURATION")
    print("=" * 60 + "\n")

    default_name = "primary" if db_num == 1 else f"db{db_num}"
    config = {
        "name": get_input("Friendly name for this connection", default_name),
        "host": get_input("Database host", "localhost"),
        "port": get_input("Port", "5432"),
        "user": get_input("Username"),
        "password": get_input("Password", secret=True),
        "database": get_input("Database name"),
        "sslmode": get_input("SSL mode", "prefer"),
        "connect_timeout": get_input("Connect timeout seconds", "10"),
        "application_name": get_input("Application name", "postgres-intelligence"),
    }

    required = ["host", "port", "user", "password", "database", "name"]
    if any(not config[key] for key in required):
        return None

    print("\nTesting connection...")
    success, message = test_connection(config)
    if success:
        print(message)
        return config

    print(f"Connection failed: {message}")
    retry = get_input("Retry this configuration? (y/n)", "y").lower()
    if retry == "y":
        return setup_database_config(db_num)
    return None


def create_env_file(configs: List[Dict[str, str]]) -> Path:
    skill_dir = Path(__file__).resolve().parent.parent
    env_path = skill_dir / ".env"

    with env_path.open("w", encoding="utf-8") as file:
        file.write("# postgres-intelligence - Database Configuration\n")
        file.write("# Auto-generated by setup.py. Do not commit this file.\n\n")

        for index, config in enumerate(configs, 1):
            file.write(f"# ===== DATABASE CONNECTION {index} =====\n")
            file.write(f"DB{index}_HOST={config['host']}\n")
            file.write(f"DB{index}_PORT={config['port']}\n")
            file.write(f"DB{index}_USER={config['user']}\n")
            file.write(f"DB{index}_PASSWORD={config['password']}\n")
            file.write(f"DB{index}_DATABASE={config['database']}\n")
            file.write(f"DB{index}_NAME={config['name']}\n")
            file.write(f"DB{index}_SSLMODE={config['sslmode']}\n")
            file.write(f"DB{index}_CONNECT_TIMEOUT={config['connect_timeout']}\n")
            file.write(f"DB{index}_APPLICATION_NAME={config['application_name']}\n\n")

    return env_path


def main() -> int:
    print("PostgreSQL Intelligence - Setup Wizard")
    print("Configure up to 10 PostgreSQL database connections.\n")

    configs: List[Dict[str, str]] = []
    first = setup_database_config(1)
    if not first:
        print("Primary database configuration is required.")
        return 1
    configs.append(first)

    for db_num in range(2, 11):
        add_next = get_input(f"Add database connection {db_num}? (y/n)", "n").lower()
        if add_next != "y":
            break
        config = setup_database_config(db_num)
        if config:
            configs.append(config)

    env_path = create_env_file(configs)
    print(f"\nConfiguration saved to: {env_path}")
    print(f"Configured {len(configs)} database connection(s):")
    for index, config in enumerate(configs, 1):
        print(f"  {index}. {config['name']} ({config['host']}:{config['port']})")

    print("\nNext steps:")
    print("  python3 scripts/config.py")
    print("  python3 scripts/db_connector.py")
    print("  python3 scripts/schema_extractor.py")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except KeyboardInterrupt:
        print("\nSetup cancelled.")
        raise SystemExit(130)
    except Exception as error:
        print(f"Error: {error}", file=sys.stderr)
        raise SystemExit(1)
